source "https://rubygems.org"

gem 'sinatra'
gem 'sequel'
gem 'sqlite3'
gem 'thin'
gem 'watchr'
gem 'json'
gem 'twitter'

group :development do
  gem 'pry'
end

group :test do
  gem 'factory_girl'
  gem 'rack-test'
end
