namespace :db do
  require "sequel"
  Sequel.extension :migration

  desc "setup test db"
  task :setuptest do
    DB = Sequel.sqlite('db/test.db')
    Sequel::Migrator.run(DB, "db/migrations", :target => 001)
    puts "<= sq:migrate:reset executed"
  end

  desc "setup dev db"
  task :setupdev do
    DB = Sequel.sqlite('db/development.db')
    Sequel::Migrator.run(DB, "db/migrations", :target => 001)
    puts "<= sq:migrate:reset executed"
  end

end

%w[unit functional integration].each do |type|
  desc "run #{type} tests"
  task "test:#{type}" do
    Dir.glob "./test/#{type}/*_test.rb" do |f|
      require "./test/test_helper"
      require f
    end
  end

  desc "run single file tests"
  task "test:#{type}:file" do
    file = "./test/#{type}/#{ENV["name"]}_test.rb"
    if File.exists? file
      require "./test/test_helper"
      require file
    else
      puts "test file not found: #{file}"
    end
  end

end
